---
- template:
    src: udev_rules_nics.j2
    dest: /etc/udev/rules.d/00-persistent-nic-name.rules
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: udev_rules_t
    selevel: s0
